### ISSUE TITLE
Old Android browser cannot connect to websocket

### ISSUE THREAD

**Issue by michaelkrog** [DRB-IT/blacktigerjs#4]
See https://github.com/DRB-IT/blacktiger-web/issues/109

**Comment by paf61** [comment]
Måske skal vi ikke bruge tid på dette, når det kan løses ved at bruge Chrome på de gamle Android-enheder?

**Comment by michaelkrog** [comment]
Enig. 

Måske vi istedet skulle have en test af om websockets er supporteret i den browser de bruger, og så give dem en bedre besked end blot Lost Connection i de tilfælde?
